[sprite_sheet.background]
texture_image = "../../assets/textures/background.png"
sprites = [{ x = 0, y = 0, width = 64, height = 48 }]

[sprite_sheet.CubedBitsLogoSmall]
texture_image = "../../assets/textures/CubedBitsLogoSmall.png"
sprites = [{ x = 0, y = 0, width = 256, height = 256 }]
